FROM node:18-alpine 

WORKDIR /app

# Copiamos package.json e instalamos dependencias
COPY package*.json ./
RUN npm install

# ¡AQUÍ ESTÁ LA MAGIA! Copiamos todo el resto de tu código fuente
COPY . .

EXPOSE 3000

CMD ["npm", "start"]