spring.application.name=asistencia
# ===============================
# CONFIGURACION DE BASE DE DATOS (MySQL)
# ===============================
# Cambia asistencia_db por el nombre de tu base de datos si es diferente
spring.datasource.url=jdbc:mysql://localhost:4003/asistencia?createDatabaseIfNotExist=true
spring.datasource.username=asistencia
# Reemplaza esto con la contrasena de tu base de datos local
spring.datasource.password=Asistencia123*

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
# update le dice a Spring que cree o actualice las tablas de la BD automaticamente segun tus clases Java
spring.jpa.hibernate.ddl-auto=update

# true te permite ver en la consola las consultas SQL que Spring esta ejecutando (muy util para aprender y debugear)
spring.jpa.show-sql=true
