spring.application.name=asistencia
# ===============================
# CONFIGURACION DE BASE DE DATOS (MySQL)
# ===============================
# Cambia 'asistencia_db' por el nombre de tu base de datos si es diferente
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# Reemplaza esto con la contrase�a de tu base de datos local
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
# 'update' le dice a Spring que cree o actualice las tablas de la BD automaticamente segun tus clases Java
spring.jpa.hibernate.ddl-auto=update

# 'true' te permite ver en la consola las consultas SQL que Spring esto ejecutando (muy util para aprender y debugear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080